

GET http://localhost:3000/showPlanets

###


POST http://localhost:3000/savePlanets
content-type: application/json

{
    "name": "Venus",
    "description": "red"
}

###

DELETE http://localhost:3000/planets/delete
content-type: application/json

{
    "index": 1
}

###

GET http://localhost:3000/specific/Pluto