

GET http://localhost:3000/showPlanets

###


POST http://localhost:3000/savePlanets
content-type: application/json

{
    "name": "testplanet",
    "color": "test"
}

###

DELETE http://localhost:3000/planets/delete
content-type: application/json

{
    "index": 1
}