

GET http://localhost:3000/showPlanets

###

GET http://localhost:3000/specific/The Sun

###


POST http://localhost:3000/savePlanets
content-type: application/json

{
    "name": "Test1",
    "description": "Testplanet"
}

###

DELETE http://localhost:3000/planets/delete/_ywvq1xgng
content-type: application/json


###

PUT http://localhost:3000/change/_vx7u1drgy
content-type: application/json

{
    "name": "Mercury2",
    "description": "Changed text"
}